cities_list = [
    'Adelaide',
    'Abu Dhabi',
    'Algiers',
    'Berlin',
    'Cairo',
    'Canberra',
    'Cape Town',
    'Gaborone',
    'Kigali',
    'Kinshasa',
    'Jerusalem',
    'Lagos',
    'London',
    'Moscow',
    'Mumbai',
    'New York',
    'Nairobi',
    'Paris',
    'Shanghai',
    'Tel Aviv',
    'Tokyo',
    'Wellington',
]