cities_list = [
    'Adelaide',
    'Abu Dhabi',
    'Algiers',
    'Berlin',
    'Beijing',
    'Cairo',
    'Canberra',
    'Doha',
    'Dubai',
    'Gaborone',
    'Ghuangzhou',
    'Jerusalem',
    'Kigali',
    'Kinshasa',
    'Kisumu',
    'Lagos',
    'London',
    'Lusaka',
    'Madrid',
    'Moscow',
    'Mombasa',
    'Migori',
    'Mumbai',
    'New York',
    'Nairobi',
    'Paris',
    'Pretoria',
    'Rabat',
    'Riyadh',
    'Shanghai',
    'singapore',
    'Tel Aviv',
    'Tokyo',
    'Toronto',
    'Tripoli',
]